//! Qwen3.6 tool-call syntax: rendering it into a prompt and reading it back.
//!
//! This checkpoint's chat template does not use the JSON-in-`<tool_call>` form
//! some Qwen releases do. It asks for nested XML-ish tags:
//!
//! ```text
//! <tool_call>
//! <function=read_file>
//! <parameter=path>
//! src/lib.rs
//! </parameter>
//! </function>
//! </tool_call>
//! ```
//!
//! Parameter values are raw text, so the declared JSON type is what decides
//! whether `42` means the number or the string. The tool schema the request
//! supplied is therefore part of parsing, not just of prompting.
//!
//! # The round trip has to preserve bytes
//!
//! An agentic client sends the assistant turn back on its next request, and the
//! server renders it into the prompt again. If those rendered bytes differ from
//! the ones the model generated by so much as a space, the new prompt is no
//! longer a prefix of the live session and the whole conversation is re-prefilled
//! from a cache boundary.
//!
//! The bytes cannot simply be carried across, because OpenAI's `arguments` is a
//! JSON string and clients are entitled to parse and re-emit it — pi 0.84.2
//! does, with `JSON.stringify`, which compacts away every space. What makes the
//! round trip exact anyway is that the model's formatting is not arbitrary: the
//! template writes a structured parameter with Jinja's `tojson`, transformers
//! configures that with Python's separators, and so the model writes
//! `[{"a": 1}]` — space after every colon and comma — because that is what it
//! was trained on. Rendering a parsed value back through [`python_json`]
//! reproduces it whatever the client did in between.
//!
//! The two sides are therefore:
//!
//! - [`ParsedToolCall::arguments_json`] builds `arguments` from the parameter
//!   text rather than from parsed values, so a client that echoes the string
//!   verbatim never had a chance to lose anything;
//! - [`render`] writes a string parameter as its contents and a structured one
//!   through [`python_json`], which lands on the model's own bytes from either
//!   an echoed or a re-serialised call.

use std::borrow::Cow;

use serde_json::Value;

const CALL_OPEN: &str = "<tool_call>";
const CALL_CLOSE: &str = "</tool_call>";
const FUNCTION_OPEN: &str = "<function=";
const FUNCTION_CLOSE: &str = "</function>";
const PARAMETER_OPEN: &str = "<parameter=";
const PARAMETER_CLOSE: &str = "</parameter>";

/// One call as the model wrote it: a name and its parameters as raw text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedToolCall {
    pub name: String,
    pub parameters: Vec<(String, String)>,
}

impl ParsedToolCall {
    /// The call's arguments as OpenAI's `arguments` field: a JSON object
    /// encoded as a string, typed by the tool's declared parameter types where
    /// they exist.
    ///
    /// The object is assembled from the parameter text rather than from parsed
    /// values, because the bytes are what has to come back. A parameter whose
    /// text is already JSON of some non-string type is copied in as it stands,
    /// keeping the model's own spacing; anything else becomes a JSON string of
    /// that exact text. A value that should be JSON but is not parseable is
    /// therefore kept as a string rather than dropped: handing the caller what
    /// the model actually wrote beats inventing a value or failing the call.
    ///
    /// The two cases stay distinguishable on the way back, which is what lets
    /// [`render`] reproduce the original markup: a JSON string always means
    /// "the parameter text is this string's contents", and any other JSON value
    /// always means "the parameter text is this value, written the way the
    /// template writes it".
    pub fn arguments_json(&self, schema: Option<&Value>) -> String {
        let properties = schema
            .and_then(|schema| schema.get("parameters"))
            .and_then(|parameters| parameters.get("properties"));
        let mut arguments = String::from("{");
        for (position, (name, raw)) in self.parameters.iter().enumerate() {
            if position > 0 {
                arguments.push(',');
            }
            let declared = properties
                .and_then(|properties| properties.get(name))
                .and_then(|property| property.get("type"))
                .and_then(Value::as_str);
            arguments.push_str(&json_string(name));
            arguments.push(':');
            arguments.push_str(&encode(raw, declared));
        }
        arguments.push('}');
        arguments
    }
}

/// Encode one parameter's text as a JSON value.
fn encode(raw: &str, declared: Option<&str>) -> String {
    // A declared string is a string whatever it looks like, so `42` stays the
    // digits the model typed. An undeclared parameter is treated like a typed
    // one: the model wrote JSON for anything structured, and a bare word simply
    // fails to parse.
    //
    // Text that parses as a JSON *string* takes the string path too, even
    // though it is valid JSON, so that the encoding stays one-to-one: were
    // `"hi"` copied in verbatim it would be indistinguishable from the escaped
    // form of the text `hi`, and rendering could not tell which to write back.
    if declared != Some("string")
        && let Ok(value) = serde_json::from_str::<Value>(raw)
        && !value.is_string()
    {
        // `from_str` accepted the text, so whatever surrounds the value is JSON
        // whitespace and trimming leaves the value itself.
        return raw.trim().to_owned();
    }
    json_string(raw)
}

/// `text` as a JSON string literal, escaped the way `serde_json` escapes.
fn json_string(text: &str) -> String {
    Value::String(text.to_owned()).to_string()
}

/// JSON with Python's default separators and the key order it was given,
/// which is what the reference template produces through Jinja's `tojson`
/// (transformers overrides it with `sort_keys=False, ensure_ascii=False`).
///
/// This is how the template writes a structured parameter value and a tool
/// definition alike, and it is why the model's own JSON carries a space after
/// every colon and comma: this is the formatting it was trained on.
///
/// `serde_json` is built with `preserve_order` so an object renders in the
/// order it arrived in, byte for byte like the reference.
pub(crate) fn python_json(value: &Value) -> String {
    match value {
        Value::Object(map) => {
            let fields: Vec<String> = map
                .iter()
                .map(|(key, value)| format!("{}: {}", json_string(key), python_json(value)))
                .collect();
            format!("{{{}}}", fields.join(", "))
        }
        Value::Array(items) => {
            let items: Vec<String> = items.iter().map(python_json).collect();
            format!("[{}]", items.join(", "))
        }
        other => other.to_string(),
    }
}

/// Split generated text into the part meant for the user and the calls it
/// requested.
///
/// The template tells the model that reasoning may precede a call but nothing
/// may follow one, so text after the last call is dropped rather than shown.
pub fn parse(text: &str) -> (String, Vec<ParsedToolCall>) {
    let Some(first) = text.find(CALL_OPEN) else {
        return (text.to_owned(), Vec::new());
    };
    let mut calls = Vec::new();
    let mut rest = &text[first..];
    while let Some(start) = rest.find(CALL_OPEN) {
        let body = &rest[start + CALL_OPEN.len()..];
        // A block ends at its own close tag. Parsing past it would let a block
        // that carries no function of its own adopt the next one's, and then
        // the scan would read that same function again from its real block.
        // A truncated final block has no close tag and simply runs to the end.
        let (block, after) = match body.find(CALL_CLOSE) {
            Some(end) => (&body[..end], Some(&body[end + CALL_CLOSE.len()..])),
            None => (body, None),
        };
        // A block that parses to nothing is skipped rather than ending the
        // scan: the blocks after it are still the model's own calls.
        if let Some(call) = parse_call(block) {
            calls.push(call);
        }
        let Some(remainder) = after else {
            break;
        };
        rest = remainder;
    }
    if calls.is_empty() {
        return (text.to_owned(), calls);
    }
    (text[..first].trim_end().to_owned(), calls)
}

/// Parse one `<function=…>…</function>` block from the text after a
/// `<tool_call>` marker.
fn parse_call(body: &str) -> Option<ParsedToolCall> {
    let open = body.find(FUNCTION_OPEN)?;
    let after_open = &body[open + FUNCTION_OPEN.len()..];
    let name_end = after_open.find('>')?;
    let name = after_open[..name_end].trim().to_owned();
    if name.is_empty() {
        return None;
    }
    let mut inner = &after_open[name_end + 1..];
    let close = inner.find(FUNCTION_CLOSE)?;
    inner = &inner[..close];
    let mut parameters = Vec::new();
    let mut cursor = inner;
    while let Some(start) = cursor.find(PARAMETER_OPEN) {
        let after = &cursor[start + PARAMETER_OPEN.len()..];
        let Some(key_end) = after.find('>') else {
            break;
        };
        let key = after[..key_end].trim().to_owned();
        let value_text = &after[key_end + 1..];
        let Some(value_end) = value_text.find(PARAMETER_CLOSE) else {
            break;
        };
        // The template frames a value with a newline on each side; anything
        // else inside the tags is the value itself.
        let value = value_text[..value_end]
            .strip_prefix('\n')
            .unwrap_or(&value_text[..value_end]);
        let value = value.strip_suffix('\n').unwrap_or(value);
        parameters.push((key, value.to_owned()));
        cursor = &value_text[value_end + PARAMETER_CLOSE.len()..];
    }
    Some(ParsedToolCall { name, parameters })
}

/// Render an assistant turn's calls back into the prompt, as the template does
/// when a tool-calling conversation is replayed.
///
/// `arguments` is OpenAI's JSON-object-as-a-string. Its members are read with
/// their own text rather than through a parsed object, which keeps the order
/// and the exact text of everything a formatting choice cannot change; what a
/// formatting choice *can* change is written the way the template writes it.
/// Between them a call the model made comes back out as the bytes it generated;
/// see the module documentation for why that matters. Arguments that are not a
/// JSON object render as a call with no parameters, which is what the tags say.
pub fn render(name: &str, arguments: &str, out: &mut String) {
    out.push_str(CALL_OPEN);
    out.push('\n');
    out.push_str(FUNCTION_OPEN);
    out.push_str(name);
    out.push_str(">\n");
    for (key, value) in object_members(arguments).unwrap_or_default() {
        out.push_str(PARAMETER_OPEN);
        out.push_str(&key);
        out.push_str(">\n");
        out.push_str(&parameter_text(value));
        out.push('\n');
        out.push_str(PARAMETER_CLOSE);
        out.push('\n');
    }
    out.push_str(FUNCTION_CLOSE);
    out.push('\n');
    out.push_str(CALL_CLOSE);
}

/// The parameter text one JSON value stands for.
///
/// A string stands for its contents, as the template's
/// `args_value | string if args_value is string` says. An object or an array
/// is re-rendered with [`python_json`] rather than copied: that is the
/// template's `tojson`, and it is the formatting the model itself writes, so
/// writing it here reproduces the model's bytes even when the arguments came
/// back from a client that re-serialised them. Anything else — a number, a
/// boolean, `null` — keeps its own text, which no formatting choice affects
/// and which a round trip through a float would round away.
fn parameter_text(value: &str) -> Cow<'_, str> {
    match value.as_bytes().first() {
        Some(b'"') => match serde_json::from_str::<String>(value) {
            Ok(text) => Cow::Owned(text),
            Err(_) => Cow::Borrowed(value),
        },
        Some(b'{' | b'[') => match serde_json::from_str::<Value>(value) {
            Ok(parsed) => Cow::Owned(python_json(&parsed)),
            Err(_) => Cow::Borrowed(value),
        },
        _ => Cow::Borrowed(value),
    }
}

/// The members of a JSON object, each value kept as the exact text it was
/// written with, in the order they were written.
///
/// `serde_json` would hand back parsed values, which are one re-serialisation
/// away from the bytes that arrived; this scan keeps the bytes. `None` means
/// the text is not a JSON object.
fn object_members(text: &str) -> Option<Vec<(String, &str)>> {
    let bytes = text.as_bytes();
    let mut at = skip_whitespace(bytes, 0);
    if bytes.get(at) != Some(&b'{') {
        return None;
    }
    at = skip_whitespace(bytes, at + 1);
    let mut members = Vec::new();
    if bytes.get(at) != Some(&b'}') {
        loop {
            if bytes.get(at) != Some(&b'"') {
                return None;
            }
            let key_end = scan_string(bytes, at)?;
            let key: String = serde_json::from_str(&text[at..key_end]).ok()?;
            at = skip_whitespace(bytes, key_end);
            if bytes.get(at) != Some(&b':') {
                return None;
            }
            let value = skip_whitespace(bytes, at + 1);
            let value_end = scan_value(bytes, value)?;
            members.push((key, &text[value..value_end]));
            at = skip_whitespace(bytes, value_end);
            match bytes.get(at) {
                Some(b',') => at = skip_whitespace(bytes, at + 1),
                Some(b'}') => break,
                _ => return None,
            }
        }
    }
    // Anything after the object means this was not one object's text.
    (skip_whitespace(bytes, at + 1) == bytes.len()).then_some(members)
}

fn skip_whitespace(bytes: &[u8], mut at: usize) -> usize {
    while matches!(bytes.get(at), Some(b' ' | b'\t' | b'\n' | b'\r')) {
        at += 1;
    }
    at
}

/// One past the end of the JSON value that starts at `at`.
fn scan_value(bytes: &[u8], at: usize) -> Option<usize> {
    match *bytes.get(at)? {
        b'"' => scan_string(bytes, at),
        b'{' | b'[' => scan_container(bytes, at),
        // A number, `true`, `false` or `null` ends at the first byte that
        // cannot be part of one.
        _ => {
            let end = bytes[at..]
                .iter()
                .position(|byte| matches!(byte, b',' | b'}' | b']' | b' ' | b'\t' | b'\n' | b'\r'))
                .map_or(bytes.len(), |offset| at + offset);
            (end > at).then_some(end)
        }
    }
}

/// One past the closing bracket of the array or object that starts at `at`.
///
/// Brackets inside a string do not nest, so strings are skipped whole.
fn scan_container(bytes: &[u8], at: usize) -> Option<usize> {
    let mut expected = Vec::new();
    let mut at = at;
    while at < bytes.len() {
        match bytes[at] {
            b'"' => at = scan_string(bytes, at)?,
            b'{' => {
                expected.push(b'}');
                at += 1;
            }
            b'[' => {
                expected.push(b']');
                at += 1;
            }
            byte @ (b'}' | b']') => {
                if expected.pop()? != byte {
                    return None;
                }
                at += 1;
                if expected.is_empty() {
                    return Some(at);
                }
            }
            _ => at += 1,
        }
    }
    None
}

/// One past the closing quote of the string that starts at `at`.
fn scan_string(bytes: &[u8], at: usize) -> Option<usize> {
    let mut at = at + 1;
    while at < bytes.len() {
        match bytes[at] {
            // Whatever an escape introduces, it is one ASCII byte, so stepping
            // over it cannot land inside a multi-byte character.
            b'\\' => at += 2,
            b'"' => return Some(at + 1),
            _ => at += 1,
        }
    }
    None
}

/// The marker that tells a streaming caller to stop showing text to the user.
pub const CALL_MARKER: &str = CALL_OPEN;

/// The marker that ends a turn.
///
/// The template instructs the model to reply with a call and *no suffix*, and
/// a turn that keeps going past one is not following it: left unbounded, this
/// checkpoint will emit call after call until it runs out of budget. Treating
/// the closing tag as the end of the turn is what makes a tool-calling turn
/// terminate, at the cost of one call per turn.
pub const CALL_END_MARKER: &str = CALL_CLOSE;

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn plain_text_has_no_calls() {
        let (content, calls) = parse("just an answer");
        assert_eq!(content, "just an answer");
        assert!(calls.is_empty());
    }

    #[test]
    fn parses_one_call_with_its_parameters() {
        let text = "I will look.\n\n<tool_call>\n<function=read_file>\n\
                    <parameter=path>\nsrc/lib.rs\n</parameter>\n\
                    <parameter=limit>\n40\n</parameter>\n</function>\n</tool_call>";
        let (content, calls) = parse(text);
        assert_eq!(content, "I will look.");
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].name, "read_file");
        assert_eq!(
            calls[0].parameters,
            vec![
                ("path".to_owned(), "src/lib.rs".to_owned()),
                ("limit".to_owned(), "40".to_owned()),
            ]
        );
    }

    #[test]
    fn parses_several_calls_in_one_turn() {
        let text = "<tool_call>\n<function=a>\n<parameter=x>\n1\n</parameter>\n\
                    </function>\n</tool_call>\n\
                    <tool_call>\n<function=b>\n</function>\n</tool_call>";
        let (content, calls) = parse(text);
        assert!(content.is_empty());
        assert_eq!(calls.len(), 2);
        assert_eq!(calls[0].name, "a");
        assert_eq!(calls[1].name, "b");
        assert!(calls[1].parameters.is_empty());
    }

    #[test]
    fn a_truncated_call_still_yields_what_completed() {
        // The turn hit its token budget after the function block closed.
        let text = "<tool_call>\n<function=a>\n<parameter=x>\n1\n</parameter>\n</function>";
        let (_, calls) = parse(text);
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].parameters, vec![("x".to_owned(), "1".to_owned())]);

        // Nothing usable yet: no closing function tag.
        let (content, calls) = parse("<tool_call>\n<function=a>\n<parameter=x>\n1");
        assert!(calls.is_empty());
        assert!(
            content.contains("<tool_call>"),
            "the text is returned as-is"
        );
    }

    #[test]
    fn a_block_never_adopts_the_next_blocks_function() {
        // Regression: the scan used to look for `<function=` past the first
        // block's own `</tool_call>`, so the empty block took the second
        // block's call and the second block then reported it again.
        let text = "<tool_call>\n</tool_call>\n\
                    <tool_call>\n<function=a>\n<parameter=x>\n1\n</parameter>\n\
                    </function>\n</tool_call>";
        let (_, calls) = parse(text);
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].name, "a");
        assert_eq!(calls[0].parameters, vec![("x".to_owned(), "1".to_owned())]);

        // The same block with text in it, and with a well-formed call ahead of
        // the malformed one rather than behind it.
        let (_, calls) = parse(
            "<tool_call>\nnot a call\n</tool_call>\n\
             <tool_call>\n<function=b>\n</function>\n</tool_call>",
        );
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].name, "b");
        let (_, calls) = parse(
            "<tool_call>\n<function=a>\n</function>\n</tool_call>\n\
             <tool_call>\nnothing here\n</tool_call>",
        );
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].name, "a");
    }

    #[test]
    fn keeps_multi_line_values_intact() {
        let text = "<tool_call>\n<function=write>\n<parameter=body>\nline one\nline two\n\
                    </parameter>\n</function>\n</tool_call>";
        let (_, calls) = parse(text);
        assert_eq!(calls[0].parameters[0].1, "line one\nline two");
    }

    #[test]
    fn typing_follows_the_declared_schema() {
        let schema = json!({
            "parameters": {"properties": {
                "path": {"type": "string"},
                "limit": {"type": "integer"},
                "deep": {"type": "boolean"},
                "opts": {"type": "object"}
            }}
        });
        let call = ParsedToolCall {
            name: "read".into(),
            parameters: vec![
                ("path".into(), "42".into()),
                ("limit".into(), "40".into()),
                ("deep".into(), "true".into()),
                ("opts".into(), "{\"a\": 1}".into()),
                ("extra".into(), "hello".into()),
            ],
        };
        let arguments = typed(&call.arguments_json(Some(&schema)));
        // A declared string stays a string even when it looks like a number.
        assert_eq!(arguments["path"], json!("42"));
        assert_eq!(arguments["limit"], json!(40));
        assert_eq!(arguments["deep"], json!(true));
        assert_eq!(arguments["opts"], json!({"a": 1}));
        // An undeclared parameter that is not JSON stays text.
        assert_eq!(arguments["extra"], json!("hello"));
        // The parameters keep the order the model wrote them in, which is part
        // of what the re-rendered prompt has to reproduce.
        assert!(
            arguments
                .as_object()
                .expect("an object")
                .keys()
                .eq(call.parameters.iter().map(|(name, _)| name))
        );
    }

    #[test]
    fn unparseable_json_is_kept_as_written() {
        let schema = json!({"parameters": {"properties": {"n": {"type": "integer"}}}});
        let call = ParsedToolCall {
            name: "f".into(),
            parameters: vec![("n".into(), "about forty".into())],
        };
        assert_eq!(
            typed(&call.arguments_json(Some(&schema)))["n"],
            json!("about forty")
        );
    }

    #[test]
    fn rendering_round_trips_through_the_parser() {
        let mut rendered = String::new();
        render(
            "read_file",
            r#"{"path":"src/lib.rs","limit":40,"deep":true}"#,
            &mut rendered,
        );
        let (content, calls) = parse(&rendered);
        assert!(content.is_empty());
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].name, "read_file");
        let schema = json!({
            "parameters": {"properties": {
                "path": {"type": "string"},
                "limit": {"type": "integer"},
                "deep": {"type": "boolean"}
            }}
        });
        assert_eq!(
            typed(&calls[0].arguments_json(Some(&schema))),
            json!({"path": "src/lib.rs", "limit": 40, "deep": true})
        );
    }

    /// The arguments string as a client would read it.
    fn typed(arguments: &str) -> Value {
        serde_json::from_str(arguments).expect("the arguments are JSON")
    }

    /// The full server round trip for one call the model generated: parse the
    /// markup, hand the client OpenAI `tool_calls`, and render what a client
    /// that echoes them back would send.
    ///
    /// This is the loop that has to be the identity function. Anything it
    /// changes moves the prompt off the live session's tokens and costs a
    /// re-prefill of the whole conversation.
    fn round_trip(markup: &str, schema: Option<&Value>) -> String {
        let (content, calls) = parse(markup);
        assert!(content.is_empty(), "the fixture is a bare call");
        assert_eq!(calls.len(), 1, "the fixture is one call");
        let arguments = calls[0].arguments_json(schema);
        // A client reads and re-emits this as a JSON string; it must be one.
        let echoed: Value =
            serde_json::from_str(&arguments).expect("the arguments the client is handed are JSON");
        assert!(echoed.is_object(), "arguments are an object: {arguments}");
        let mut rendered = String::new();
        render(&calls[0].name, &arguments, &mut rendered);
        rendered
    }

    fn call_markup(parameters: &str) -> String {
        format!("<tool_call>\n<function=edit>\n{parameters}</function>\n</tool_call>")
    }

    #[test]
    fn a_calls_own_json_spacing_survives_the_round_trip() {
        // The shape that cost a re-prefill: the model writes JSON with a space
        // after each colon, and the schema declares the parameter an array, so
        // nothing about it is a string the old path would have copied through.
        let schema = json!({"parameters": {"properties": {
            "path": {"type": "string"},
            "edits": {"type": "array"}
        }}});
        let markup = call_markup(
            "<parameter=path>\n/tmp/CLAUDE.md\n</parameter>\n\
             <parameter=edits>\n\
             [{\"oldText\": \"Qwen3-Coder-Next\", \"newText\": \"Qwen3.6-35B-A3B\"}]\n\
             </parameter>\n",
        );
        assert_eq!(round_trip(&markup, Some(&schema)), markup);
    }

    #[test]
    fn every_parameter_shape_survives_the_round_trip() {
        let schema = json!({"parameters": {"properties": {
            "text": {"type": "string"},
            "count": {"type": "integer"},
            "nested": {"type": "object"}
        }}});
        for value in [
            // Multi-line text, which is what a `write` call carries.
            "line one\nline two\n\nline four",
            // A string that is JSON punctuation, or looks like a number.
            "{\"not\": \"parsed\"}",
            "42",
            // Quotes and backslashes, which the JSON string encoding has to
            // escape and the render side has to unescape back.
            "he said \"hi\"\\ and left\ttabbed",
            // Unicode, which must not come back as `\uXXXX` escapes.
            "café → 日本語 — ✅",
            "",
        ] {
            let markup = call_markup(&format!("<parameter=text>\n{value}\n</parameter>\n"));
            assert_eq!(round_trip(&markup, Some(&schema)), markup, "text {value:?}");
        }
        for value in [
            // JSON in the formatting the template taught the model: a space
            // after every colon and comma.
            "[{\"a\": 1, \"b\": [2, 3]}]",
            "{\"brackets\": \"] } [ {\", \"escaped\": \"a\\\"b\"}",
            "{\"unicode\": \"café → 日本語\", \"newline\": \"a\\nb\"}",
            "[]",
            "{}",
            // Scalars, whose text no formatting choice affects.
            "12",
            "1.5e-3",
            "true",
            "null",
            // A JSON string as the whole value: it round-trips as the text it
            // is, quotes included, rather than being unwrapped.
            "\"quoted\"",
        ] {
            let markup = call_markup(&format!("<parameter=nested>\n{value}\n</parameter>\n"));
            assert_eq!(
                round_trip(&markup, Some(&schema)),
                markup,
                "nested {value:?}"
            );
        }
    }

    #[test]
    fn an_undeclared_parameter_survives_without_a_schema() {
        // With no tools declared for the name, every parameter is untyped, and
        // the round trip still has to be exact.
        let markup = call_markup(
            "<parameter=a>\nplain words\n</parameter>\n\
             <parameter=b>\n[1, 2, 3]\n</parameter>\n\
             <parameter=c>\n{\"k\": \"v\"}\n</parameter>\n",
        );
        assert_eq!(round_trip(&markup, None), markup);
    }

    #[test]
    fn a_client_that_reserialises_the_arguments_still_lands_on_the_model_bytes() {
        // pi 0.84.2 parses `arguments` and re-emits it with `JSON.stringify`,
        // so the model's spacing is gone before the call comes back. It is
        // recovered rather than mourned: the template's own `tojson` puts a
        // space after every colon and comma, which is why the model writes them
        // there, so re-rendering the parsed value writes what the model wrote.
        let schema = json!({"parameters": {"properties": {"edits": {"type": "array"}}}});
        let markup =
            call_markup("<parameter=edits>\n[{\"old\": \"a\", \"new\": \"b\"}]\n</parameter>\n");
        let (_, calls) = parse(&markup);
        let arguments: Value =
            serde_json::from_str(&calls[0].arguments_json(Some(&schema))).expect("JSON");
        for echoed in [
            // Compacted, as `JSON.stringify` leaves it.
            arguments.to_string(),
            // Indented, as a client that pretty-prints leaves it.
            serde_json::to_string_pretty(&arguments).expect("pretty JSON"),
        ] {
            let mut rendered = String::new();
            render("edit", &echoed, &mut rendered);
            assert_eq!(rendered, markup, "echoed as {echoed:?}");
        }
    }

    #[test]
    fn a_value_the_model_formatted_its_own_way_is_normalised() {
        // The inverse of the case above, and the price of it: JSON the model
        // wrote in some other formatting comes back as the template's, which is
        // the one formatting both sides can agree on without the bytes.
        let schema = json!({"parameters": {"properties": {"opts": {"type": "object"}}}});
        let markup = call_markup("<parameter=opts>\n{\n  \"a\": 1,\n  \"b\": 2\n}\n</parameter>\n");
        assert_eq!(
            round_trip(&markup, Some(&schema)),
            call_markup("<parameter=opts>\n{\"a\": 1, \"b\": 2}\n</parameter>\n")
        );
    }

    #[test]
    fn arguments_that_are_not_an_object_render_no_parameters() {
        for arguments in ["", "null", "[1]", "\"text\"", "{", "not json"] {
            let mut rendered = String::new();
            render("f", arguments, &mut rendered);
            assert_eq!(
                rendered, "<tool_call>\n<function=f>\n</function>\n</tool_call>",
                "arguments {arguments:?}"
            );
        }
    }
}
